version: "3.8"

services:
  db:
    image: postgres:16.2
    env_file:
      - ./.env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    # volumes:
    # - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env.test
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
